name: Scrapper
on:
  push:
  schedule:
    - cron: '0 9 * * *'  # Run the job daily at 09:00 AM UTC
    
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Running the Python script
        run: python scrapper.py
        env:
          SHIFTBOARD_USERNAME: ${{ secrets.SHIFTBOARD_USERNAME }}
          SHIFTBOARD_PASSWORD: ${{ secrets.SHIFTBOARD_PASSWORD }}
          MY_TELEGRAM_CHAT_ID: ${{ secrets.MY_TELEGRAM_CHAT_ID }}
          TELEGRAMBOT_TOKEN: ${{ secrets.TELEGRAMBOT_TOKEN }}
          SHIFTBOARD_LOGIN_URL: ${{ secrets.SHIFTBOARD_LOGIN_URL }}

      - name: Push updated file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Github Actions"
          author_email: "actions@github.com"
          message: "Updated 🥳"
          add: "."
          push: "https://github.com/mh-firouzjah/shiftboard_scrapper.git"
